name: Endpoints status check
on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "uci-cubesat-server-dev"
          heroku_email: "chillinthestar@outlook.com"
#      - name: Install Python 3
#        uses: actions/setup-python@v1
#        with:
#          python-version: 3.10.4
#      - name: Run test with pytest
#        run: |
#          cd src/python/test
#          pip install pytest
#          pip install requests
#          pip install datetime
#          pytest test_endpoint.py
#      - uses: akhileshns/heroku-deploy@v3.12.12
#        with:
#          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
#          heroku_app_name: "uci-cubesat-server"
#          heroku_email: "chillinthestar@outlook.com"
