name: Endpoints Status Check w/ Deploy
on:
  push:
    branches: [main]
  pull_request:
    branches:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy to Heroku Development Server Environment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "uci-cubesat-server-dev"
          heroku_email: "chillinthestar@outlook.com"
      - name: Install Python3.10
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.7
      - name: Install PyTest requirements and run PyTest
        run: |
          cd src/python/test
          pip install -r "requirements.txt"
          pytest test_endpoint.py
      - name: Deploy to Heroku Production Server Environment
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "uci-cubesat-server"
          heroku_email: "chillinthestar@outlook.com"
