name: Endpoints status check
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # deploy to a heroku app specifically created for testing only
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "uci-cubesat-server-dev"
          heroku_email: "chillinthestar@outlook.com"
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.10.4
      # run tests from ./src/python/test/test_endpoint.py
      - name: Run test with pytest
        run: |
          cd src/python/test
          pip install -r "requirements.txt"
          pytest test_endpoint.py
      # When tests pass, deploy this commit to production
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "uci-cubesat-server"
          heroku_email: "chillinthestar@outlook.com"
